AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a two instance stack

Parameters:
  InstanceType:
    Description: Instance type to launch
    Type: String
    Default: t3.small
  ImageId:
    Description: AMI Id
    # This will use the latest AIS Image
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /AIS/AMI/AmazonLinux2/Id
    #
    # Alternatively, you can pin AMI versions like this
    #Type: String
    #Default: '{{resolve:ssm:/AIS/AMI/AmazonLinux2/Id:27}}'
    # Check the latest paramter version like this:
    # $ aws ssm get-parameter --name "/AIS/AMI/AmazonLinux2/Id"
    # {
    #     "Parameter": {
    #         "Name": "/AIS/AMI/AmazonLinux2/Id",
    #         "Type": "String",
    #         "Value": "ami-05751724d5c878717",
    #         "Version": 28,
    #         "LastModifiedDate": 1553301486.036,
    #         "ARN": "arn:aws:ssm:us-west-2:117117185606:parameter/AIS/AMI/AmazonLinux2/Id"
    #     }
    # }
  S3ArtifactBucket:
    Description: Name of Bucket for Artifacts
    Type: String
  S3ArtifactKey:
    Default: twoinstancesnlb.zip
    Description: The file name of the source artifact, such as myfolder/myartifact.zip
    Type: String
  EnclaveId:
    Description: 'AWS Account ID of the enclave where we should advertise the service'
    Type: AWS::SSM::Parameter::Value<String>
    Default: /AIS/AccountSetup/EnclaveId

Resources:

# The Test Instance
  TestEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: TestInstanceProfile
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - Fn::ImportValue: ais-shared-services-sg-SS-SG
        - Ref: TestSecurityGroup
      SubnetId:
        Fn::ImportValue: ais-provided-vpc-PrivSubnet1
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName}-Test-Instance"
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash
            set -eux

            # Set default region
            AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            REGION=$(echo $AZ | sed 's/.$//')
            aws configure set region $REGION

  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Sub: "${AWS::StackName} SG"
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp:
          Fn::ImportValue: ais-provided-vpc-VPCCIDR
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp:
          Fn::ImportValue: ais-provided-vpc-VPCCIDR

  TestInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: TestInstanceRole

  TestInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/AISSystemLogsPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/ais-permissions-boundaries'

# The Application Instance
  AppEC2InstanceA:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: AppInstanceProfile
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - Fn::ImportValue: ais-shared-services-sg-SS-SG
        - Ref: AppSecurityGroup
      SubnetId:
        Fn::ImportValue: ais-provided-vpc-PrivSubnet1
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName}-App-Instance"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            set -eux
            teardown() {
              exit_code=$?
              [ -d "$tmpdir" ] && rm -rf $tmpdir
              /opt/aws/bin/cfn-signal       \
                -e $exit_code               \
                --stack ${AWS::StackName}   \
                --resource AppEC2Instance   \
                --region ${AWS::Region}
              trap - EXIT ERR INT TERM
            }
            trap teardown EXIT ERR INT TERM

            # Bootstrap application installation here
            AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            REGION=$(echo $AZ | sed 's/.$//')
            export AWS_DEFAULT_REGION=$REGION
            aws configure set region $REGION
            aws s3 cp s3://${S3ArtifactBucket}/${S3ArtifactKey} /tmp
            mkdir -p /tmp/artifact
            sudo unzip -o /tmp/${S3ArtifactKey} -d /tmp/artifact
            cd /tmp/artifact/playbooks && /usr/bin/ansible-playbook -v --connection=local -i "localhost," /tmp/artifact/playbooks/configure_instances.yaml

  AppEC2InstanceB:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: AppInstanceProfile
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - Fn::ImportValue: ais-shared-services-sg-SS-SG
        - Ref: AppSecurityGroup
      SubnetId:
        Fn::ImportValue: ais-provided-vpc-PrivSubnet2
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName}-App-Instance"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            set -eux
            teardown() {
              exit_code=$?
              [ -d "$tmpdir" ] && rm -rf $tmpdir
              /opt/aws/bin/cfn-signal       \
                -e $exit_code               \
                --stack ${AWS::StackName}   \
                --resource AppEC2Instance   \
                --region ${AWS::Region}
              trap - EXIT ERR INT TERM
            }
            trap teardown EXIT ERR INT TERM

            # Bootstrap application installation here
            AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            REGION=$(echo $AZ | sed 's/.$//')
            export AWS_DEFAULT_REGION=$REGION
            aws configure set region $REGION
            aws s3 cp s3://${S3ArtifactBucket}/${S3ArtifactKey} /tmp
            mkdir -p /tmp/artifact
            sudo unzip -o /tmp/${S3ArtifactKey} -d /tmp/artifact
            cd /tmp/artifact/playbooks && /usr/bin/ansible-playbook -v --connection=local -i "localhost," /tmp/artifact/playbooks/configure_instances.yaml

  AppEC2InstanceC:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: AppInstanceProfile
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - Fn::ImportValue: ais-shared-services-sg-SS-SG
        - Ref: AppSecurityGroup
      SubnetId:
        Fn::ImportValue: ais-provided-vpc-PrivSubnet3
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName}-App-Instance"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            set -eux
            teardown() {
              exit_code=$?
              [ -d "$tmpdir" ] && rm -rf $tmpdir
              /opt/aws/bin/cfn-signal       \
                -e $exit_code               \
                --stack ${AWS::StackName}   \
                --resource AppEC2Instance   \
                --region ${AWS::Region}
              trap - EXIT ERR INT TERM
            }
            trap teardown EXIT ERR INT TERM

            # Bootstrap application installation here
            AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            REGION=$(echo $AZ | sed 's/.$//')
            export AWS_DEFAULT_REGION=$REGION
            aws configure set region $REGION
            aws s3 cp s3://${S3ArtifactBucket}/${S3ArtifactKey} /tmp
            mkdir -p /tmp/artifact
            sudo unzip -o /tmp/${S3ArtifactKey} -d /tmp/artifact
            cd /tmp/artifact/playbooks && /usr/bin/ansible-playbook -v --connection=local -i "localhost," /tmp/artifact/playbooks/configure_instances.yaml

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Sub: "${AWS::StackName} SG"
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp:
          Fn::ImportValue: ais-provided-vpc-VPCCIDR
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp:
          Fn::ImportValue: ais-provided-vpc-VPCCIDR

  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: AppInstanceRole

  AppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/AISSystemLogsPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/ais-permissions-boundaries'
      Policies:
        - PolicyName: ArtifactsRetrieval
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: RetrievingArtifacts
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListObjects
                Resource:
                  Fn::Sub: "arn:aws:s3:::${S3ArtifactBucket}/*"


#############################
# The Network Load Balancer
#
# NOTE: In order to create a VPC Endpoint over the DirectConnect, you will need
#       to ensure that your load balancer is using all three Availability Zones.
#       That is defined in the Subnets block below.
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      Type: network
      Subnets:
        - Fn::ImportValue: ais-provided-vpc-PrivSubnet1
        - Fn::ImportValue: ais-provided-vpc-PrivSubnet2
        - Fn::ImportValue: ais-provided-vpc-PrivSubnet3
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName} Load Balancer"
        - Key: Privatelinks
          Value: to be exposed via privatelinks
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: "true"

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${AWS::StackName}-TG'
      Port: 8080
      Protocol: TCP
      HealthCheckPort: "8080"
      TargetType: instance
      Targets:
        - Id: !Ref AppEC2InstanceA
          Port: 8080
        - Id: !Ref AppEC2InstanceB
          Port: 8080
        - Id: !Ref AppEC2InstanceC
          Port: 8080
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '20'
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: TargetGroup
      LoadBalancerArn: !Ref 'LoadBalancer'
      Port: 8080
      Protocol: TCP

# The VPC Endpoint Service
  EndpointService:
    Type: AWS::EC2::VPCEndpointService
    Properties:
      NetworkLoadBalancerArns:
        - !Ref LoadBalancer
      AcceptanceRequired: False
  EndpointServicePermission:
    Type: AWS::EC2::VPCEndpointServicePermissions
    Properties:
      ServiceId: !Ref 'EndpointService'
      AllowedPrincipals:
        - !Sub 'arn:aws:iam::${EnclaveId}:root'

# The Interface VPC Endpoint, which goes into the AIS account. The
# DNS name will be registered in the output value below.
  AISVpcEndpoint:
    Type: Custom::VpcEndpointRequestor
    DependsOn: EndpointServicePermission
    Properties:
      ServiceToken: !ImportValue ais-vpc-endpoint-requestor-arn
      EndpointServiceID: !Ref EndpointService
      ip_permissions:
        - from_port: 8080
          to_port: 8080
          ip_ranges:
            - cidr_ip: 17.0.0.0/8
              description: AppleDesktop
            - cidr_ip: 10.0.0.0/8
              description: AnotherCIDR

Outputs:
  TestInstanceID:
    Description: The Test Instance ID
    Value: !Ref TestEC2Instance
    Export:
      Name: !Sub "${AWS::StackName}-Test-Instance-ID"
  AppELBDNS:
    Description: The Application NLB DNS Name
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-App-ELB-DNS"
  EndpointServiceId:
    Description: VPC Endpoint Service ID
    Value:
      Ref: EndpointService
    Export:
      Name: !Sub "${AWS::StackName}-VPCE-SVC-ID"
  PrivateLinkDNSName:
    Description: The PrivateLink DNS Name
    Value: !GetAtt AISVpcEndpoint.dnsname
    Export:
      Name: !Sub "${AWS::StackName}-VPCE-DNSName"
  AppInstanceAIP:
    Description: The Application Instance IP Address
    Value: !GetAtt AppEC2InstanceA.PrivateIp
    Export:
      Name: !Sub "${AWS::StackName}-App-Instance-A-IP"
  AppInstanceBIP:
      Description: The Application Instance IP Address
      Value: !GetAtt AppEC2InstanceB.PrivateIp
      Export:
        Name: !Sub "${AWS::StackName}-App-Instance-B-IP"
  AppInstanceCIP:
      Description: The Application Instance IP Address
      Value: !GetAtt AppEC2InstanceC.PrivateIp
      Export:
        Name: !Sub "${AWS::StackName}-App-Instance-C-IP"
