AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a two instance stack

Parameters:
  InstanceType:
    Description: Instance type to launch
    Type: String
    Default: t3.micro
  ImageId:
    Description: AMI Id
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /AIS/AMI/AmazonLinux2/Id
  S3ArtifactBucket:
    Description: Name of Bucket for Artifacts
    Type: String
  S3ArtifactKey:
    Default: twoinstancesnlb.zip
    Description: The file name of the source artifact, such as myfolder/myartifact.zip
    Type: String
  AZNumber:
    Description: The Index which defines the Availability Zone to use (1, 2, or 3)
    Type: Number
    AllowedValues: [1, 2, 3]
    Default: 1

Resources:

# The Test Instance
  TestEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: TestInstanceProfile
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - Fn::ImportValue: ais-shared-services-sg-SS-SG
        - Ref: TestSecurityGroup
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: ais-provided-vpc-PrivSubnet${AZNumber}
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName}-Test-Instance"
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash
            set -eux

            # Set default region
            AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            REGION=$(echo $AZ | sed 's/.$//')
            aws configure set region $REGION

  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Sub: "${AWS::StackName} SG"
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp:
          Fn::ImportValue: ais-provided-vpc-VPCCIDR
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp:
          Fn::ImportValue: ais-provided-vpc-VPCCIDR

  TestInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: TestInstanceRole

  TestInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/AISSystemLogsPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/ais-permissions-boundaries'

# The Application Instance
  AppEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: AppInstanceProfile
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - Fn::ImportValue: ais-shared-services-sg-SS-SG
        - Ref: AppSecurityGroup
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: ais-provided-vpc-PrivSubnet${AZNumber}
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName}-App-Instance"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            set -ex
            teardown() {
              exit_code=$?
              [ -d "$tmpdir" ] && rm -rf $tmpdir
              /opt/aws/bin/cfn-signal       \
                -e $exit_code               \
                --stack ${AWS::StackName}   \
                --resource AutoScalingGroup \
                --region ${AWS::Region}
              trap - EXIT ERR INT TERM
            }
            trap teardown EXIT ERR INT TERM

            # Bootstrap application installation here
            AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            REGION=$(echo $AZ | sed 's/.$//')
            export AWS_DEFAULT_REGION=$REGION
            aws configure set region $REGION
            aws s3 cp s3://${S3ArtifactBucket}/${S3ArtifactKey} /tmp
            mkdir -p /tmp/artifact
            sudo unzip -o /tmp/${S3ArtifactKey} -d /tmp/artifact
            /usr/bin/ansible-playbook -v --connection=local -i "localhost," /tmp/artifact/playbooks/configure_instances.yaml

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Sub: "${AWS::StackName} SG"
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp:
          Fn::ImportValue: ais-provided-vpc-VPCCIDR
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp:
          Fn::ImportValue: ais-provided-vpc-VPCCIDR

  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: AppInstanceRole

  AppInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:aws:iam::${AWS::AccountId}:policy/AISSystemLogsPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/ais-permissions-boundaries'
      Policies:
        - PolicyName: ArtifactsRetrieval
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: RetrievingArtifacts
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListObjects
                Resource:
                  Fn::Sub: "arn:aws:s3:::${S3ArtifactBucket}/*"


#############################
# The Network Load Balancer
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      Type: network
      Subnets:
        - Fn::ImportValue:
            Fn::Sub: ais-provided-vpc-PrivSubnet1
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName} Load Balancer"

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${AWS::StackName}-TG'
      Port: 8080
      Protocol: TCP
      HealthCheckPort: "8080"
      TargetType: instance
      Targets:
        - Id: !Ref AppEC2Instance
          Port: 8080
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '20'
      VpcId:
        Fn::ImportValue: ais-provided-vpc-VPCID

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: TargetGroup
      LoadBalancerArn: !Ref 'LoadBalancer'
      Port: 8080
      Protocol: TCP


Outputs:
  TestInstanceID:
    Description: The Test Instance ID
    Value: !Ref TestEC2Instance
    Export:
      Name: !Sub "${AWS::StackName}-Test-Instance-ID"
  AppInstanceID:
    Description: The Application Instance ID
    Value: !Ref AppEC2Instance
    Export:
      Name: !Sub "${AWS::StackName}-App-Instance-ID"
  AppInstanceIP:
    Description: The Application Instance IP Address
    Value: !GetAtt AppEC2Instance.PrivateIp
    Export:
      Name: !Sub "${AWS::StackName}-App-Instance-IP"
  AppELBDNS:
    Description: The Application NLB DNS Name
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-App-ELB-DNS"
