AWSTemplateFormatVersion: "2010-09-09"
Description: ECS@Apple - Container Registry

Parameters:
  RepositoryName:
    Type: String
    Description: Repository Name
    MinLength: 2
    MaxLength: 256
    AllowedPattern: (?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*

Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  RepositoryArn:
    Value: !GetAtt MyRepository.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ARN"

  RepositoryUri:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}
    Export:
      Name: !Sub "${AWS::StackName}-URI"
