AWSTemplateFormatVersion: 2010-09-09
Description: ECS@Apple - LoadBalancer

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      Type: network
      Subnets:
        - !ImportValue ais-provided-vpc-PrivSubnet1
        - !ImportValue ais-provided-vpc-PrivSubnet2
        - !ImportValue ais-provided-vpc-PrivSubnet3
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${AWS::StackName} Load Balancer"
        - Key: Privatelinks
          Value: to be exposed via privatelinks
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: "true"

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${AWS::StackName}-TG"
      Port: 80
      Protocol: TCP
      HealthCheckPort: "80"
      TargetType: ip
      VpcId: !ImportValue ais-provided-vpc-VPCID

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: TCP

Outputs:
  LoadBalancer:
    Export:
      Name: !Sub "${AWS::StackName}-LB"
    Value: !Ref LoadBalancer
  TargetGroup:
    Export:
      Name: !Sub "${AWS::StackName}-TG"
    Value: !Ref TargetGroup
  Listener:
    Export:
      Name: !Sub "${AWS::StackName}-Listener"
    Value: !Ref Listener
