# Define global names
COMMON_NAME=hello-ecs
NLB_STACK_NAME="$COMMON_NAME-nlb"
APP_STACK_NAME="$COMMON_NAME-app"
VPCE_STACK_NAME="$COMMON_NAME-vpce"

# Used by FARGATE
ECR_STACK_NAME="$COMMON_NAME-ecr"
ECR_REPO_NAME="httpd"

# Define default values
LAUNCH_TYPE=EC2
WORKER_INSTANCE_TYPE=t3.medium
NUM_NODES=1
MIN_NUM_NODES=1
MAX_NUM_NODES=3
CONTAINER_IMAGE=httpd:2.4
