apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudwatch-agent
  namespace: amazon-cloudwatch
spec:
  template:
    spec:
      containers:
        - name: cloudwatch-agent
          image: amazon/cloudwatch-agent:1.245315.0
          ports:
            - containerPort: 8125
              hostPort: 8125
              protocol: UDP