{
 "title": "Kubernetes Golden Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU Limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores)"
    }
   ]
  },
  {
   "title": "Namespace CPU Limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)"
    }
   ]
  },
  {
   "title": "Cluster Memory Limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes)"
    }
   ]
  },
  {
   "title": "Node Memory Limits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (node)"
    }
   ]
  },
  {
   "title": "Pods Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (pod) / sum(label_join(kube_pod_container_resource_limits_memory_bytes,\"pod\", \"\", \"pod\")) by (pod)"
    }
   ]
  },
  {
   "title": "Container Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (container, pod) / sum(label_join(kube_pod_container_resource_limits_memory_bytes,\"container_name\", \"\", \"container\")) by (container, pod)"
    }
   ]
  },
  {
   "title": "Pods CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Container CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total[5m])) by (container,pod)"
    }
   ]
  },
  {
   "title": "Pod Network I/O Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total[5m])) by (pod)\n"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total[5m])) by (pod)\n"
    }
   ]
  },
  {
   "title": "Container Network I/O Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total[5m])) by (container,pod)\n"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total[5m])) by (pod)\n"
    }
   ]
  },
  {
   "title": "Cached Memory per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Cached Memory per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{image!=\"\",name=~\"^k8s_.*\",container!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (container,pod)"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "graph",
   "description": "DISK seconds Read/ Write Latency.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_write_time_seconds_total{kubernetes_io_hostname=~\"^$Node$\"}[2m])/ rate(node_disk_writes_completed_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
     "legendFormat": "{{device}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Latency ",
   "type": "graph",
   "description": "Disk seconds Read Latency.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(rate(node_disk_read_time_seconds_total{kubernetes_io_hostname=~\"^$Node$\"}[2m])/ rate(node_disk_reads_completed_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
     "legendFormat": "{{device}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]) + rate(node_disk_written_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m])",
     "legendFormat": "{{device}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "graph",
   "description": "Number of bytes read from the monitored disk per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m])",
     "legendFormat": "{{device}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "graph",
   "description": "Number of bytes written to the monitored disk per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m])",
     "legendFormat": "{{device}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Request",
   "type": "graph",
   "description": "Number of read requests sent to the monitored disk per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{kubernetes_io_hostname=~\"^$Node$\"}[2m])",
     "legendFormat": "{{device}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Write Request",
   "type": "graph",
   "description": "Number of write requests sent to the monitored disk per second.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{kubernetes_io_hostname=~\"^$Node$\"}[2m])",
     "legendFormat": "{{device}}:{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Device Error",
   "type": "graph",
   "description": "Whether an error occurred while getting statistics for the given device.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_device_error{kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Filesystem Device Error: {{alias}} [{{fstype}}] ({{device}}) {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Space Used",
   "type": "graph",
   "description": "Filesystem used space.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{kubernetes_io_hostname=~\"^$Node$\"} - node_filesystem_avail_bytes{kubernetes_io_hostname=~\"^$Node$\"}) / node_filesystem_size_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "Filesystem Space Used: {{alias}} [{{fstype}}] ({{device}}) {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem Inodes Used ",
   "type": "graph",
   "description": "Filesystem used file nodes.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{kubernetes_io_hostname=~\"^$Node$\"} / node_filesystem_files{kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "Filesystem Inodes: {{alias}} [{{fstype}}] ({{device}}) {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Interface State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_network_up{kubernetes_io_hostname=~\"^$Node$\",device!=\"lo\"}",
     "legendFormat": "Interface: {{instance}} [{{device}}]",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Interface Speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_network_transmit_queue_length{kubernetes_io_hostname=~\"^$Node$\",device!=\"lo\"}",
     "legendFormat": "Interface: {{instance}} [{{device}}]",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network IN | OUT Traffic Bytes",
   "type": "graph",
   "description": "IN | OUT Traffic rate.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\",device!=\"lo\"}[2m])",
     "legendFormat": "IN: {{instance}}  [{{ device }}] ",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\",device!=\"lo\"}[2m])",
     "legendFormat": "OUT: {{instance}}  [{{ device }}] ",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network IN | OUT Packets",
   "type": "graph",
   "description": "Network Packets for IN/OUT.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_packets_total{kubernetes_io_hostname=~\"^$Node$\",device!=\"lo\"}[2m])",
     "legendFormat": "IN: {{instance}}  [{{ device }}] ",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_packets_total{kubernetes_io_hostname=~\"^$Node$\",device!=\"lo\"}[2m])",
     "legendFormat": "OUT: {{instance}}  [{{ device }}] ",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Transmission Error",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_errs_total{kubernetes_io_hostname=~\"^$Node$\",device!~\"lo\"}[2m]) / rate(node_network_transmit_packets_total{kubernetes_io_hostname=~\"^$Node$\",device!~\"lo\"}[2m])",
     "legendFormat": "OUT: {{instance}} [{{device}}]",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Receive Error",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_errs_total{kubernetes_io_hostname=~\"^$Node$\",device!~\"lo\"}[2m]) / rate(node_network_receive_packets_total{kubernetes_io_hostname=~\"^$Node$\",device!~\"lo\"}[2m])",
     "legendFormat": "IN: {{instance}} [{{device}}]",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Processes Running & Blocked",
   "type": "graph",
   "description": "Kernel/System statistics:\n- Number of processes in runnable state.\n-   Number of processes blocked waiting for I/O to complete.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked{kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "node_procs_running{kubernetes_io_hostname=~\"^$Node$\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}