CLUSTER_NAME=mskatapple
INSTANCE_TYPE=kafka.t3.small
VOLUME_SIZE=100
ENHANCED_MONITORING=DEFAULT
KAFKA_VERSION=2.2.1
BROKER_NODES=3

CLUSTER_STACK_NAME=msk-$CLUSTER_NAME
TC_STACK_NAME=$CLUSTER_STACK_NAME-tc
CLIENT_STACK_NAME=$CLUSTER_STACK_NAME-client
